config/routes.rb
Rails.application.routes.draw do
  root to: 'nested/books#index'

  namespace :nested do
    resources :books
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/nested.rb
module Nested
  def self.table_name_prefix
    "nested_"
  end
end

app/models/nested/book.rb
class Nested::Book < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/nested/base_controller.rb
class Nested::BaseController < ApplicationController
  layout 'application'

  before_action :set_nested_book, only: %i[ show edit update destroy ]

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nested_book
      @nested_book = Nested::Book.find(params[:id])
    end
end

app/controllers/nested/books_controller.rb
class Nested::BooksController < Nested::BaseController
  # GET /nested/books or /nested/books.json
  def index
    @nested_books = Nested::Book.all
  end

  # GET /nested/books/1 or /nested/books/1.json
  def show
    render @nested_book
  end

  # GET /nested/books/new
  def new
    @nested_book = Nested::Book.new
  end

  # GET /nested/books/1/edit
  def edit
  end

  # POST /nested/books or /nested/books.json
  def create
    @nested_book = Nested::Book.new(nested_book_params)

    respond_to do |format|
      if @nested_book.save
        format.html { redirect_to nested_book_url(@nested_book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @nested_book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @nested_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nested/books/1 or /nested/books/1.json
  def update
    respond_to do |format|
      if @nested_book.update(nested_book_params)
        format.html { redirect_to nested_book_url(@nested_book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @nested_book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @nested_book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nested/books/1 or /nested/books/1.json
  def destroy
    @nested_book.destroy

    respond_to do |format|
      format.html { redirect_to nested_books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def nested_book_params
      params.fetch(:nested_book, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nested/books_helper.rb
module Nested::BooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NestedControllersAndLayouts</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <p>Application Layout</p>

    <%= yield %>
  </body>
</html>

app/views/nested/books/_book.html.erb
<div id="<%= dom_id book %>">
</div>

app/views/nested/books/_form.html.erb
<%= form_with(model: nested_book) do |form| %>
  <% if nested_book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(nested_book.errors.count, "error") %> prohibited this nested_book from being saved:</h2>

      <ul>
        <% nested_book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/nested/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", nested_book: @nested_book %>

<br>

<div>
  <%= link_to "Show this book", @nested_book %> |
  <%= link_to "Back to books", nested_books_path %>
</div>

app/views/nested/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Books</h1>

<div id="nested_books">
  <% @nested_books.each do |nested_book| %>
    <%= render nested_book %>
    <p>
      <%= link_to "Show this book", nested_book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_nested_book_path %>

app/views/nested/books/new.html.erb
<h1>New book</h1>

<%= render "form", nested_book: @nested_book %>

<br>

<div>
  <%= link_to "Back to books", nested_books_path %>
</div>

app/views/nested/books/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @nested_book %>

<div>
  <%= link_to "Edit this book", edit_nested_book_path(@nested_book) %> |
  <%= link_to "Back to books", nested_books_path %>

  <%= button_to "Destroy this book", @nested_book, method: :delete %>
</div>